Repository replit/river-python, pull requests merged in 2024-11, with the labels that each got.

#104 [bug/client codegen] local_discriminator should be stable
  replit_river/codegen/client.py
Labels: bug

#105 [feat] Expose containing module for servergen
  replit_river/codegen/client.py
  replit_river/codegen/run.py
  replit_river/codegen/server.py
Labels: enhancement, minor

#107 [chore] Switch to uv
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  Dockerfile
  flake.nix
  poetry.lock
  pyproject.toml
  uv.lock
Labels: chore

#112 Missing some signatures from #111
  replit_river/rpc.py
  tests/conftest.py
Labels: bug

#113 chore/decompose monolithic client gen
  replit_river/codegen/client.py
  tests/conftest.py
Labels: minor

#114 Limiting FILE_HEADER
  replit_river/codegen/client.py
Labels: chore, patch

#116 bug/minor oddities
  LICENSE
  replit_river/codegen/client.py
Labels: bug

#117 bugfix: Ensure both trace fields are set if tracing is used
  replit_river/rpc.py
Labels: bug

#118 Revert "Turns out pydantic has never been able to correctly discern a RiverNotType"
  replit_river/codegen/client.py
Labels: bug

#122 use empty context in restore budget task
  replit_river/rate_limiter.py
Labels: minor

#121 bugfix: include streaming procedure errors in traces
  replit_river/client.py
  replit_river/client_session.py
  replit_river/rpc.py
  replit_river/session.py
  tests/conftest.py
  tests/river_fixtures/logging.py
  tests/test_communication.py
  tests/test_opentelemetry.py
Labels: bug

#126 Improve typing
  Makefile
  pyproject.toml
  replit_river/rpc.py
  tests/test_message_buffer.py
  uv.lock
Labels: chore

#127 Resolve pytest warnings
  pyproject.toml
  tests/conftest.py
  tests/river_fixtures/clientserver.py
  uv.lock
Labels: chore
