Repository replit/river-python, pull requests merged in 2024-12, with the labels that each got.

#128 chore/ruff formatting
  .github/workflows/ci.yml
  Makefile
  pyproject.toml
  replit_river/codegen/client.py
  replit_river/codegen/server.py
  scripts/format.sh
  scripts/lint.sh
  tests/river_fixtures/clientserver.py
  tests/test_handshake.py
  uv.lock
Labels: chore

#123 Implement RPC timeouts
  pyproject.toml
  replit_river/client.py
  replit_river/client_session.py
  replit_river/codegen/client.py
  replit_river/rpc.py
  replit_river/session.py
  replit_river/task_manager.py
  tests/codegen/rpc/generated/__init__.py
  tests/codegen/rpc/generated/test_service/__init__.py
  tests/codegen/rpc/generated/test_service/rpc_method.py
  tests/codegen/rpc/schema.json
  tests/codegen/stream/generated/__init__.py
  tests/codegen/stream/generated/test_service/__init__.py
  tests/codegen/stream/generated/test_service/stream_method.py
  tests/codegen/stream/schema.json
  tests/codegen/stream/test_stream.py
  tests/codegen/test_rpc.py
  tests/test_communication.py
  tests/test_opentelemetry.py
Labels: enhancement

#130 Address incorrect packaging information
  pyproject.toml
  uv.lock
Labels: bug

#129 Don't record GeneratorExit errors in stream RPC spans
  replit_river/client.py
  replit_river/client_session.py
  tests/test_opentelemetry.py
Labels: bug, patch

#131 Fix accidental truncation of RPC timeouts
  replit_river/client_session.py
  tests/test_timeout.py
Labels: bug, patch
